insert into users (user_name, user_email, is_active_user) values
('Indira', 'ijordeson0@umich.edu', false),
('Concordia', 'coglessane1@opensource.org', false),
('Stephanie', 'scarlyle2@prlog.org', true),
('Bonni', 'bscogings3@cpanel.net', true),
('Gino', 'gmacquaker4@patch.com', true),
('Selene', 'sjedrzejewski5@jiathis.com', true),
('Nathanael', 'nzannelli6@miibeian.gov.cn', false),
('Waly', 'wpittle7@canalblog.com', false),
('Libbi', 'lkalderon8@youtube.com', false),
('Willdon', 'whearne9@house.gov', true),
('Eugenio', 'ebengefield1@topsy.com', false),
('Guillaume', 'ghuncoot2@baidu.com', false),
('Bartram', 'bware3@wikia.com', true),
('Odille', 'odomini4@deviantart.com', false),
('Keelby', 'kbucham5@state.gov', true),
('Ernie', 'eslavin6@digg.com', false),
('Rosemonde', 'rmarkussen7@wiley.com', false),
('Christiane', 'ccadany8@nationalgeographic.com', false),
('Henrie', 'hthurbon9@jiathis.com', true),
('Celle', 'cenderwicka@csmonitor.com', false),
('Lewie', 'lthridgouldb@earthlink.net', true),
('Gerianna', 'gmorffewc@mac.com', true),
('Mara', 'mdrewettd@t.co', false),
('Pammi', 'pviviene@plala.or.jp', false),
('Glori', 'ghucksf@lycos.com', false),
('Alexandr', 'aantonnikovg@hibu.com', false),
('Brook', 'bfosth@deviantart.com', true),
('Ferdinand', 'fivantyevi@etsy.com', false),
('Lucias', 'leldinj@geocities.jp', true),
('Hilliary', 'hmattheeuwk@csmonitor.com', false),
('Bree', 'bmilaml@symantec.com', true),
('Suzi', 'smarshamm@technorati.com', false),
('Teresina', 'tforcaden@google.ru', false),
('Andonis', 'amouleo@joomla.org', false),
('Dom', 'dmurtp@netscape.com', true),
('Riva', 'rjanaudq@telegraph.co.uk', false),
('Bud', 'bsargersonr@pbs.org', false),
('Bel', 'bputtrells@cargocollective.com', false),
('Winnie', 'wchildest@newsvine.com', false),
('Montgomery', 'mglideu@statcounter.com', true),
('Virgie', 'vonionv@dailymotion.com', true),
('Dorthea', 'dwolveyw@rambler.ru', false),
('Josefina', 'jwhottonx@creativecommons.org', true),
('Friederike', 'fsambellsy@google.com.au', true),
('Monique', 'mdemangelz@google.cn', true),
('Tim', 'tbutterfill10@gravatar.com', true),
('Oralla', 'opollastrone11@last.fm', true),
('Sybyl', 'syuryichev12@zdnet.com', true),
('Harley', 'htuppeny13@amazon.co.jp', true),
('Cherrita', 'cbraniff14@ezinearticles.com', false),
('Margy', 'mnetherclift15@scribd.com', false),
('Kaile', 'kgreggersen16@mlb.com', false),
('Robena', 'rbaytrop17@mapy.cz', true),
('Johnathon', 'jclemo18@over-blog.com', true),
('Brigitta', 'borcott19@tiny.cc', true),
('Dita', 'dfrere1a@networksolutions.com', true),
('Dyanna', 'dchartres1b@state.tx.us', true),
('Chase', 'clavall1c@xing.com', false),
('Lacie', 'lgothup1d@smh.com.au', false);

INSERT INTO category (category_name, description, user_id, is_active_category) VALUES
('Customer Insight', 'A modern and sleek design with plenty of natural light', 1, true),
('Administrative Assistance', 'A bohemian-inspired oasis with plants and tapestries', 3, true),
('Regulatory Affairs', 'A cozy cabin retreat nestled in the woods', 5, true),
('RCS', 'A beachy and coastal vibe with nautical accents', 7, true),
('Financial Accounting', 'A beachy and coastal vibe with nautical accents', 9, true),
('HP Storage', 'A cozy and inviting space perfect for relaxation', 10, true),
('TSM', 'A beachy and coastal vibe with nautical accents', 1, true),
('Events Coordination', 'A vibrant and energetic space with bold patterns and artwork', 3, false),
('RLC', 'A modern and sleek design with plenty of natural light', 5, true),
('Machine Tools', 'An eclectic mix of vintage and contemporary decor', 7, false),
('Energy', 'A vibrant and energetic space with bold patterns and artwork', 9, false),
('MVT', 'A minimalist and clean aesthetic with pops of color', 10, false),
('NCLB', 'A modern and sleek design with plenty of natural light', 1, true),
('MCMS', 'A beachy and coastal vibe with nautical accents', 3, true),
('Tds', 'A rustic and charming atmosphere with a fireplace', 5, false),
('Bathrooms', 'A glamorous and luxurious setting with crystal chandeliers', 7, false),
('z/VM', 'A cozy cabin retreat nestled in the woods', 10, true),
('Virtual PC', 'A glamorous and luxurious setting with crystal chandeliers', 1, true),
('LDPE', 'A cozy and inviting space perfect for relaxation', 3, false),
('SV', 'A rustic and charming atmosphere with a fireplace', 5, true),
('DMT', 'A cozy cabin retreat nestled in the woods', 7, true),
('PMO Design', 'A cozy and inviting space perfect for relaxation', 9, false),
('Federal Grants Management', 'A beachy and coastal vibe with nautical accents', 10, true),
('VLC', 'A minimalist and clean aesthetic with pops of color', 1, true),
('CDMA2000', 'An eclectic mix of vintage and contemporary decor', 3, true),
('Rugs', 'A minimalist and clean aesthetic with pops of color', 5, false),
('ICD-9', 'A cozy and inviting space perfect for relaxation', 7, true),
('DWDM', 'A bohemian-inspired oasis with plants and tapestries', 9, true),
('Vaccines', 'A cozy cabin retreat nestled in the woods', 10, false);

INSERT INTO expense (amount, date, description, category_id, users_id, is_active_expense) VALUES
(50.0, '2024-01-01', 'Lunch at restaurant', 1, 1, true),
(15.0, '2024-01-02', 'Bus fare', 1, 1, true),
(100.0, '2024-01-03', 'Electricity bill', 2, 3, true),
(20.0, '2024-01-04', 'Movie tickets', 2, 3, true),
(300.0, '2024-01-05', 'Groceries', 3, 5, true),
(835.52, '2023-02-25', 'Dried Apple', 4, 7, false),
(436.7, '2021-12-06', 'Crab Meat Claw Pasteurise', 5, 9, false),
(249.7, '2022-12-16', 'Mustard - Pommery', 6, 10, true),
(355.07, '2022-01-29', 'Corn - Mini', 7, 1, false),
(652.49, '2024-07-31', 'Oil - Olive, Extra Virgin', 8, 3, true),
(706.81, '2022-07-06', 'Coke - Diet, 355 Ml', 9, 5, false),
(638.38, '2020-07-05', 'Parsley Italian - Fresh', 10, 7, true),
(691.74, '2022-06-05', 'Stock - Veal, Brown', 11, 9, false),
(529.1, '2021-05-06', 'Baking Powder', 11, 9, true),
(844.28, '2024-05-26', 'Cocktail Napkin Blue', 12, 10, false),
(120.79, '2023-01-16', 'Salt - Seasoned', 12, 10, true),
(64.87, '2022-04-07', 'Ecolab - Solid Fusion', 12, 10, true),
(50.76, '2023-04-27', 'Tuna - Bluefin', 13, 1, false),
(448.17, '2022-03-21', 'Juice - Tomato, 48 Oz', 13, 1, true),
(691.73, '2021-02-17', 'Yukon Jack', 20, 5, true),
(96.93, '2020-03-09', 'Garbage Bags - Black', 25, 3, true),
(7.24, '2021-06-11', 'Island Oasis - Pina Colada', 27, 7, false),
(787.83, '2020-10-31', 'Arizona - Plum Green Tea', 27, 7, true),
(32.32, '2023-01-01', 'Chicken Thigh - Bone Out', 20, 5, true),
(638.04, '2021-05-12', 'Pumpkin - Seed', 21, 7, true),
(583.86, '2024-06-20', 'Chickensplit Half', 21, 7, false),
(75.62, '2024-02-01', 'Sprouts - Peppercress', 17, 10, true),
(953.19, '2023-12-04', 'Potatoes - Yukon Gold, 80 Ct', 17, 10, false),
(526.64, '2024-09-28', '7up Diet, 355 Ml', 17, 10, false),
(199.73, '2022-02-06', 'Wine - Alsace Gewurztraminer', 14, 3, false),
(829.76, '2020-06-07', 'Shrimp - Tiger 21/25', 6, 10, true),
(7.8, '2022-11-23', 'Baking Soda', 9, 5, true),
(811.61, '2021-10-04', 'Wonton Wrappers', 20, 5, true),
(100.53, '2021-06-14', 'Soupfoamcont12oz 112con', 20, 5, false),
(740.8, '2024-08-06', 'Sausage - Meat', 12, 10, true),
(801.63, '2020-04-03', 'Mangoes', 12, 10, true),
(348.72, '2021-08-24', 'Olives - Stuffed', 12, 10, true);